# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check NPM version
        id: check-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          CURRENT_NAME=$(node -p "require('./package.json').name")
          LATEST_VERSION=$(npm show $CURRENT_NAME version)
          echo "Current version: $CURRENT_VERSION"
          echo "Latest version: $LATEST_VERSION"
          echo "build_id=$(test $CURRENT_VERSION != $LATEST_VERSION && echo true || echo false)"
      
  publish-npm:
    needs: build
    # if: ${{ needs.build.outputs['needs-publish'] == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: HHH
        run: |
          echo ${{ needs.build['outputs']['build_id'] }}
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
      #     registry-url: https://registry.npmjs.org/
      # - run: npm ci
      # - run: npm publish
      # - run: |
      #     NEW_VERSION=$(node -p "require('./package.json').version")
      #     git tag $NEW_VERSION
      #     git push origin $NEW_VERSION
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
